services:
  tiddl:
    build: .
    container_name: tiddl
    restart: unless-stopped
    environment:
      - TZ=Europe/Bratislava
    volumes:
      - ./data:/data
      - /Volumes/DeliRAID5/Media/Music:/music
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
